import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { GetStaticProps } from 'next'

const inter = Inter({ subsets: ['latin'] })

export default function Home({characters}: any) {
  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        { JSON.stringify(characters) }

        
        
      </Head>

      </div>
    
  );
};


export const getStaticProps: GetStaticProps = async(context) => {
  
  const data = await fetch("https://rickandmortyapi.com/api/character");
  const {results} = await data.json();

  return {
    props: {
      characters: results,
    },
  };
};